# Generated by Django 3.0.4 on 2020-03-09 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='score',
            new_name='elo_score',
        ),
    ]
