# Generated by Django 3.0.4 on 2020-03-05 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.EmailField(max_length=254)),
                ('score', models.SmallIntegerField(default=1500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('release', models.CharField(blank=True, max_length=10)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'In Review'), (1, 'Open'), (2, 'Rejected'), (3, 'Completed')], default=0)),
            ],
        ),
    ]
